<?
DEFINE(WPNEL_REDIRECTING,'Redirecting...');
DEFINE(WPNEL_REDIRECT1,'You were going to the redirect link, but something did not work properly.<br>Please, click ');
DEFINE(WPNEL_REDIRECT2,'HERE ');
DEFINE(WPNEL_REDIRECT3,' to go to ');
DEFINE(WPNEL_REDIRECT4,' manually. ');
DEFINE(WPNEL_PLUGIN_HOMEPAGE,'Plugin home page');
DEFINE(WPNEL_FEEDBACK,'Feedback');
DEFINE(WPNEL_PATH_TO_GOTO,'Path to redirect file "goto.php"');
DEFINE(WPNEL_DEFAULT,'Default');
DEFINE(WPNEL_IF_MODE_REWRITE,'If you use mode rewrite for cute urls, you can do the following');
DEFINE(WPNEL_PUT_HERE_SMTH_LIKE,'Put here smth like');
DEFINE(WPNEL_PUT_LINE_LIKE,'Put the line like');
DEFINE(WPNEL_TO_YOUR_FILE,'to your file');
DEFINE(WPNEL_THEN_APACHE_LEVEL_REDIRECT,'Then your server will make redirect on apache level, without using of goto.php file.');
DEFINE(WPNEL_TO_YOUR_FILE,'to your file');
DEFINE(WPNEL_THEN_APACHE_LEVEL_REDIRECT,'Then your server will make redirect on apache level, without using of goto.php file.');
DEFINE(WPNEL_MASK_LINKS_IN_POSTS,'Mask links in your posts');
DEFINE(WPNEL_MASK_LINKS_IN_COMMENTS,'Mask links in comments`s posts');
DEFINE(WPNEL_MASK_LINKS_IN_AUTHORS,'Mask comments authors`s links');
DEFINE(WPNEL_HINT,'That plugins allows you to mask all external links and make them internal - using PHP file with location header, or mod rewrite. Yeah, by the way - it does not change anything in the base - only replaces links on output.<br>P.S. It doesn`t mask internal links.');
DEFINE(WPNEL_SAVE_CHANGES,'Save changes');
DEFINE(WPNEL_CONFIGURATION,'Configuration');
?>