<?
DEFINE(WPNEL_REDIRECTING,'Перенаправляю...');
DEFINE(WPNEL_REDIRECT1,'Вы должны были перейти по ссылке автоматически, но что-то не получилось...<br>Пожалуйста, нажмите ');
DEFINE(WPNEL_REDIRECT2,'СЮДА ');
DEFINE(WPNEL_REDIRECT3,' чтобы перейти на ');
DEFINE(WPNEL_REDIRECT4,' вручную. ');
DEFINE(WPNEL_PLUGIN_HOMEPAGE,'Страница плагина');
DEFINE(WPNEL_FEEDBACK,'Отзывы');
DEFINE(WPNEL_PATH_TO_GOTO,'Путь к редирект файлу "goto.php"');
DEFINE(WPNEL_DEFAULT,'По умолчанию');
DEFINE(WPNEL_IF_MODE_REWRITE,'Если вы используете mode rewrite для создания красивых адресов, можно сделать так');
DEFINE(WPNEL_PUT_HERE_SMTH_LIKE,'Напишите сюда что-то вроде');
DEFINE(WPNEL_PUT_LINE_LIKE,'Напишите строку вроде');
DEFINE(WPNEL_TO_YOUR_FILE,'в ваш файл');
DEFINE(WPNEL_THEN_APACHE_LEVEL_REDIRECT,'Тогда ваш сервер будет делать перенаправление на уровне apache, без использования файла goto.php');
DEFINE(WPNEL_MASK_LINKS_IN_POSTS,'Маскировать ссылки в ваших сообщениях');
DEFINE(WPNEL_MASK_LINKS_IN_COMMENTS,'Макировать ссылки в комментариях');
DEFINE(WPNEL_MASK_LINKS_IN_AUTHORS,'Маскировать ссылки авторов комментариев');
DEFINE(WPNEL_HINT,'Этот плагин позволяет заменить все внешние ссылки на внутренние - при помощи PHP файла с перенпаправлением, или  mod rewrite. Да, между прочим - он не меняет ничего в базе и не пишет туда - только заменяет ссылки на выводе.<br>P.S. Внутренние ссылки плагин не маскирует:).');
DEFINE(WPNEL_SAVE_CHANGES,'Сохранить изменения');
DEFINE(WPNEL_CONFIGURATION,'Настройки');
?>