<?php
DEFINE(WPNEL_REDIRECTING,'Weiterleitung erfolgt...');
DEFINE(WPNEL_REDIRECT1,'Sie wollten einem Verweis folgen, aber etwas hat nicht richtig funktioniert.<br>Bitte klicken Sie ');
DEFINE(WPNEL_REDIRECT2,'HIER ');
DEFINE(WPNEL_REDIRECT3,', um auf ');
DEFINE(WPNEL_REDIRECT4,' zu gelangen. ');
DEFINE(WPNEL_PLUGIN_HOMEPAGE,'Plugin-Website');
DEFINE(WPNEL_FEEDBACK,'Rückmeldung');
DEFINE(WPNEL_PATH_TO_GOTO,'Pfad zu der Datei "goto.php"');
DEFINE(WPNEL_DEFAULT,'Standard');
DEFINE(WPNEL_IF_MODE_REWRITE,'Falls Sie mod_rewrite für hübsche URLs verwenden, können Sie folgendes tun');
DEFINE(WPNEL_PUT_HERE_SMTH_LIKE,'Fügen Sie hier etwas ein wie');
DEFINE(WPNEL_PUT_LINE_LIKE,'Fügen Sie die Zeile');
DEFINE(WPNEL_TO_YOUR_FILE,'Ihrer Datei hinzu');
DEFINE(WPNEL_THEN_APACHE_LEVEL_REDIRECT,'Dann wird Ihr Server die Umleitung direkt ohne Umweg über die Datei goto.php vornehmen.');
DEFINE(WPNEL_MASK_LINKS_IN_POSTS,'Verweise in Beiträgen verschleiern');
DEFINE(WPNEL_MASK_LINKS_IN_COMMENTS,'Verweise in Kommentaren verschleiern');
DEFINE(WPNEL_MASK_LINKS_IN_AUTHORS,'Verweise der Kommentierenden verschleiern');
DEFINE(WPNEL_HINT,'Dieses Plugin ermöglicht es Ihnen, alle externen Links zu verstecken oder in interne umzuwandeln - mittels PHP-Umleitung oder besonderer Linktags oder -attribute. Ach, übrigens - es ändert nichts am Kern - ersetzt die Verweise nur bei der Ausgabe.<br>P.S. Es maskiert keine internen oder ausgeschlossenen Verweise.');
DEFINE(WPNEL_SAVE_CHANGES,'Änderungen speichern');
DEFINE(WPNEL_CONFIGURATION,'Konfiguration');
DEFINE(WPNEL_LANGUAGE,'Sprache');
DEFINE(WPNEL_NO_REDIRECT,'Keine URL-Umleitung festgelegt. Kann Anfrage nicht beantworten.');
DEFINE(WPNEL_EXCLUDE_URLS,'Schließen Sie URLs aus, die Sie nicht verschleiern möchten (alle URLs, die mit diesen Zeilen beginnen, werden nicht geändert). Fügen Sie eine Adresse pro Zeile mit Präfix ein (zum Beispiel "http://jehy.ru")');
DEFINE(WPNEL_ADD_NOFOLLOW,'<b>rel=nofollow</b> für verschleierte Links einfügen (für Google)');
DEFINE(WPNEL_ADD_BLANK,'<b>target="blank"</b> für alle Links einfügen (sie werden in einem neuen Fenster geöffnet)');
DEFINE(WPNEL_PUT_NOINDEX,'Verschleierte Verweise mit <b>&lt;noindex&gt;link&lt;/noindex&gt;</b> umgeben (für die Yandex-Suchmaschine)');
DEFINE(WPNEL_DISABLE_MASK_LINKS,'URL-Rewrite aller Verweise deaktivieren (der <b>noindex</b>-Tag und <b>rel=nofollow</b> genügen völlig)');
DEFINE(WPNEL_DEFAULT_OPTIONS,'<h3>Globale Verschleierung</h3>(Sie können das Plugin auch für einzelne Beiträge deaktivieren)');
DEFINE(WPNEL_DEFAULT_POLICY,'Voreinstellung aus Pluginoptionen verwenden');
DEFINE(WPNEL_MASK,'Verweise verschleiern');
DEFINE(WPNEL_DONT_MASK,'Verweise nicht verschleiern');
DEFINE(WPNEL_PERPOST_SETTINGS,'Linkverschleierung für diesen Beitrag');
?>

