<?php
/**
 * French Language Pack for plugin No External Links by Jehy.ru
 * Copyrights iTx Technologies (www.itx-technologies.com)
 * Licensed under GPL v.3
 * lang.fr_FR.inc 2010-02-12 16:34
 * v1.0
 *  */

DEFINE(WPNEL_REDIRECTING,'Redirection...');
DEFINE(WPNEL_REDIRECT1,'Vous alliez être redirigé(e) mais un problème est survenu.<br />Veuillez cliquez ');
DEFINE(WPNEL_REDIRECT2,'ICI ');
DEFINE(WPNEL_REDIRECT3,' pour aller à ');
DEFINE(WPNEL_REDIRECT4,' manuellement. ');
DEFINE(WPNEL_PLUGIN_HOMEPAGE,'Page d\'accueil du plugin');
DEFINE(WPNEL_FEEDBACK,'Commentaires');
DEFINE(WPNEL_PATH_TO_GOTO,'Chemin vers le fichier de redirection "goto.php"');
DEFINE(WPNEL_DEFAULT,'Défaut');
DEFINE(WPNEL_IF_MODE_REWRITE,'Si vous utilisez mod rewrite pour de jolies URLs, vous pouvez faire ceci');
DEFINE(WPNEL_PUT_HERE_SMTH_LIKE,'Mettez ici quelque chose du genre');
DEFINE(WPNEL_PUT_LINE_LIKE,'Mettez la lige comme');
DEFINE(WPNEL_TO_YOUR_FILE,'vers votre fichier');
DEFINE(WPNEL_THEN_APACHE_LEVEL_REDIRECT,'Ainsi votre serveur redirigera au niveau Apache sans utiliser le fichier goto.php.');
DEFINE(WPNEL_TO_YOUR_FILE,'vers votre fichier');
DEFINE(WPNEL_THEN_APACHE_LEVEL_REDIRECT,'Ainsi votre serveur redirigera au niveau Apache sans utiliser le fichier goto.php.');
DEFINE(WPNEL_MASK_LINKS_IN_POSTS,'Masquer les liens dans vos articles');
DEFINE(WPNEL_MASK_LINKS_IN_COMMENTS,'Masquer les liens dans les commentaires');
DEFINE(WPNEL_MASK_LINKS_IN_AUTHORS,'Masquer les liens des auteurs qui commentent');
DEFINE(WPNEL_HINT,'Ce plugin vous permet the masquer tous les liens externes et les rend internes ou cachés - en utilisant une redirection PHP ou des liens spéciaux de tags et d\'attributs.  Ouais, en passant le plugin ne change en rien la base; il remplace seulement le lien lors de la sortie.<br>P.S. Il ne masque pas les liens internes et exclus.');
DEFINE(WPNEL_SAVE_CHANGES,'Enregister les changements');
DEFINE(WPNEL_CONFIGURATION,'Configuration');
DEFINE(WPNEL_LANGUAGE,'Langues');
DEFINE(WPNEL_NO_REDIRECT,'Désolé, aucun lien de redirection n\'a été spécifié.  Nous ne pouvons compléter la requête.');
DEFINE(WPNEL_EXCLUDE_URLS,'Exclure les URLs que vous ne voulez pas masquer (toutes les URLs, commençant par celles-ci, ne seront pas masquées).  Mettez une adresse par ligne, incluant le préfix (par exemple, "http://jehy.ru")');
DEFINE(WPNEL_ADD_NOFOLLOW,'Ajouter <b>rel=nofollow</b> pour les liens masqués (pour Google)');
DEFINE(WPNEL_ADD_BLANK,'Ajouter <b>target="blank"</b> pour tous les liens (les liens ouvriront dans une autre fenêtre)');
DEFINE(WPNEL_PUT_NOINDEX,'Entourer les liens masqués du tag <b>&lt;noindex&gt;link&lt;/noindex&gt;</b> (pour l\'engin de recherche Yandex)');
DEFINE(WPNEL_DISABLE_MASK_LINKS,'Désactiver la réécriture des URLs pour tous les liens (sulement le tag <b>noindex</b> et <b>rel=nofollow</b> peuvent suffir)');
DEFINE(WPNEL_DEFAULT_OPTIONS,'<h3>Paramètres du masquage des lienss</h3>(Vous pouvez aussi désactiver le plugin pour chaque publication)');
DEFINE(WPNEL_DEFAULT_POLICY,'Utiliser la politique par défaut des paramètre du plugin');
DEFINE(WPNEL_MASK,'Masquer les liens');
DEFINE(WPNEL_DONT_MASK,'Ne pas masquer les liens');
DEFINE(WPNEL_PERPOST_SETTINGS,'Masque les liens pour cette publicationLink masking for this post');
?>