<?php
DEFINE(WPNEL_REDIRECTING,'Перанакіроўваю...');
DEFINE(WPNEL_REDIRECT1,'Вы павінны былі перайсці па спасылцы аўтаматычна, але нешта не атрымалася...<br>Калі ласка, націсніце ');
DEFINE(WPNEL_REDIRECT2,'СЮДЫ ');
DEFINE(WPNEL_REDIRECT3,' каб перайсці на ');
DEFINE(WPNEL_REDIRECT4,' уручную. ');
DEFINE(WPNEL_PLUGIN_HOMEPAGE,'Старонка плагіна');
DEFINE(WPNEL_FEEDBACK,'Водгукі');
DEFINE(WPNEL_PATH_TO_GOTO,'Шлях да рэдырэкту файлу "goto.php"');
DEFINE(WPNEL_DEFAULT,'Па змаўчанні');
DEFINE(WPNEL_IF_MODE_REWRITE,'Калі вы выкарыстаеце mode rewrite для стварэння прыгожых адрасоў, можна зрабіць так');
DEFINE(WPNEL_PUT_HERE_SMTH_LIKE,'Напішыце сюды нешта накшталт');
DEFINE(WPNEL_PUT_LINE_LIKE,'Напішыце радок накшталт');
DEFINE(WPNEL_TO_YOUR_FILE,'у ваш файл');
DEFINE(WPNEL_THEN_APACHE_LEVEL_REDIRECT,'Тады ваш сервер будзе рабіць перанакіраванне на ўзроўні apache, без выкарыстання файла goto.php');
DEFINE(WPNEL_MASK_LINKS_IN_POSTS,'Маскіраваць спасылкі ў вашых паведамленнях');
DEFINE(WPNEL_MASK_LINKS_IN_COMMENTS,'Маскіраваць спасылкі ў каментарах');
DEFINE(WPNEL_MASK_LINKS_IN_AUTHORS,'Маскіраваць спасылкі аўтараў каментароў');
DEFINE(WPNEL_HINT,'Гэты плагін дазваляе замяніць усе знешнія спасылкі на ўнутраныя, або схаваць іх - пры дапамозе PHP рэдырэкта, або  адмысловых тэгаў і атрыбутаў спасылак. Так, паміж іншым - ён не змяняе нічога ў базе і не піша туды - толькі замяняе спасылкі на выснове.<br>P.S. Унутраныя і выключаныя спасылкі плагін не маскіруе:).');
DEFINE(WPNEL_SAVE_CHANGES,'Захаваць змены');
DEFINE(WPNEL_CONFIGURATION,'Налады');
DEFINE(WPNEL_LANGUAGE,'Мова');
DEFINE(WPNEL_NO_REDIRECT,'Выбачыце, не знойдзена шляхі редиректа, немагчыма здзейсніць пераход.');
DEFINE(WPNEL_EXCLUDE_URLS,'Адрасы-выключэнні, да якіх не будзе ўжывацца маскіроўка (да ўсіх, якія пачынаюцца з дадзенага тэксту, па кожным адрасе - з новага радка, уключаючы прэфікс (напрыклад, http://jehy.ru))');
DEFINE(WPNEL_ADD_NOFOLLOW,'Дадаваць <b>rel=nofollow</b> для маскируемых спасылак (кахае google)');
DEFINE(WPNEL_ADD_BLANK,'Дадаваць <b>target="blank"</b> для ўсіх спасылак (будуць адчыняцца ў новым акне)');
DEFINE(WPNEL_PUT_NOINDEX,'Атачаць спасылкі тэгам <b>&lt;noindex&gt;спасылка&lt;/noindex&gt;</b>  (для yandex)');
DEFINE(WPNEL_DISABLE_MASK_LINKS,'Выключыць падмену шляхоў для спасылак (калі вам досыць тэга <b>noindex</b> і атрыбуту <b>rel=nofollow</b>)');
DEFINE(WPNEL_DEFAULT_OPTIONS,'<h2>Глабальныя налады для маскіроўкі спасылак</h2>(Вы можаце адмяніць дзеянне плагіна  на пэўныя пасты)');

DEFINE(WPNEL_DEFAULT_POLICY,'Выкарыстаць агульныя налады плагіна');
DEFINE(WPNEL_MASK,'Маскіраваць спасылкі');
DEFINE(WPNEL_DONT_MASK,'Не маскіраваць спасылкі');
DEFINE(WPNEL_PERPOST_SETTINGS,'Маскіроўка спасылак для гэтага паста');
?>
